Drop the test-app version to 3.28 to invoke bug
At this point, the test-app no longer works due to "TypeError: decorator
is not a function" coming from @cached not being available on the
@glimmer/tracking import for SomeUtil.

Note that ember-auto-import is still all the way up to date.